### PR TITLE
[FIXED] Fix lane height and scroll to see the cards

### PR DESCRIPTION
**Pull request by MaheshKonne**
- Added global styles to set 100% height
- Wrapped lane with a wrapper to set srcoll bar
- Added snapshot tests to lane and board, so that it covers all static html and css

### CODE REVIEW

**Comment by lourenci** [comment]
Hi, @MaheshKonne. Thanks for PR.

Could you please put some print screen from before and after this changes?

**Comment by MaheshKonne** [comment]
earlier, if we have more cards in a lane, the page gets a scrollbar and the user cant see other lanes which are having few cards. Now the user will get a scroll within the lane so that page height won't change. Please refer to the attached images.

First scenario, where we cant see other lanes


Scrollbar within the lane

**Comment by lourenci** [comment]
I think this has to do with the issue #97.

What if we pass a prop to change the behaviour to this change? It was what we have discussed on that issue.

**Comment by lourenci** [comment]
Hi, @MaheshKonne. The board in `yarn start` does not scroll down at all in this change. I think this change should not take place without the user specifying the `height` prop explicitly.

**Comment by Sabrinovsky** [comment]
Hi @MaheshKonne, first of all thanks for the PR. 
We are going to give more attention to the lib, so, if you still interested could you please solve the conflicts so we can test it?

**Pull request closed without merging**
